{% set name = "azure-servicebus" %}
{% set version = "7.12.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3f0759731ad2211c68eb4b21e5bca29827f7d6ff0272bdc7eef103c1c13f8322

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - azure-core >=1.28.0
    - isodate >=0.6.0
    - typing-extensions >=4.6.0

test:
  imports:
    - azure.servicebus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Service Bus Client Library for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/Azure/azure-sdk-for-python
  doc_url: https://azure.github.io/azure-sdk-for-python/servicebus.html

extra:
  recipe-maintainers:
    - xylar
    - Maxyme
