{% set name = "azure-servicebus" %}
{% set version = "7.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-servicebus-{{ version }}.tar.gz
  sha256: b11bf569eaf77c30d8a76f88b93c08713fd36188d9cc6dabf71eadb10eb742f9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - azure-core <2.0.0,>=1.28.0
    - isodate >=0.6.0
    - typing-extensions >=4.0.1

test:
  imports:
    - azure.servicebus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Service Bus Client Library for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/Azure/azure-sdk-for-python
  doc_url: https://azure.github.io/azure-sdk-for-python/servicebus.html

extra:
  recipe-maintainers:
    - xylar
    - Maxyme
