{% set name = "azure-servicebus" %}
{% set version = "7.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a75e9a61435ca3ad3a797f1d8bf4fdd0d873eba9e5d383894ac87ef5e1a70cf0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - azure-core >=1.28.0
    - isodate >=0.6.0
    - typing_extensions >=4.6.0

test:
  imports:
    - azure.servicebus
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Service Bus Client Library for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/Azure/azure-sdk-for-python
  doc_url: https://azure.github.io/azure-sdk-for-python/servicebus.html

extra:
  recipe-maintainers:
    - xylar
    - Maxyme
